agents:
  image:
    tag: 7.55.0
    tagSuffix: jmx
datadog:
  apiKey: $KEY
  logs:
    enabled: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
  env:
    - name: KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
